(deftheme dvvc
  "Created 2012-07-28.")

(custom-theme-set-faces
 'dvvc
 '(default ((t (:inherit nil :stipple nil :background "#262736" :foreground "#c2c2c2" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 128 :width normal :foundry "unknown" :family "Inconsolata"))))
 '(cursor ((t (:background "#505474")))) ;#204a87
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#a40000"))))
 '(minibuffer-prompt ((t (:foreground "#dfbc58"))))
 '(highlight ((t (:foreground "#e1e1e0" :background "#babdb6"))))
 '(region ((t (:background "#3d5b6c"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#8cc4ff"))))
 '(trailing-whitespace ((t (:background "#ef2929"))))
 '(font-lock-builtin-face ((t (:foreground "#dee19d"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#d4a168" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#52C865")))) ; :weight bold))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#83D3A8" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#dfbc58"))))  ;; :weight bold))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#5acdb9"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#4794cd"))))
 '(font-lock-type-face ((t (:foreground "#e05252"))))
 '(font-lock-variable-name-face ((t (:foreground "#cc5ca0"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#ff4242" :inherit (error)))))
 '(button ((t (:underline t :inherit (link)))))
 '(link ((t (:underline t :foreground "#204a87"))))
 '(link-visited ((t (:underline t :foreground "#3465a4" :inherit (link)))))
 '(fringe ((t (:background "#526780"))))
 '(header-line ((t (:box nil :foreground "#333333" :background "#e5e5e5" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:background "#c2c2c2" :foreground "#262736" :box (:line-width -1 :style released-button)))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:inherit mode-line :background "#888a85" :foreground "#2e3436" :box (:line-width -1 :style released-button) :weight light))))
 '(isearch ((t (:foreground "#ffffff" :background "#ce5c00"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:background "#e9b96e"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'dvvc)
